import { Component, OnInit } from "@angular/core";
import { TextModel } from "../../../models/body.text.model";

@Component({
  selector: "app-marine",
  templateUrl: "./marine.component.html",
  styleUrls: ["./marine.component.scss"]
})
export class MarineComponent implements OnInit {
  bg = "marine.png";
  list = [];
  paragraphs = [
    `The Titan Emporium offer a range of compressor solution for the marine industry
from breathing air compressor to on board solution for vessels`,

    `On board a ship, compressed air is used for several purposes. On the basis of application,
different air compressors are kept for a particular usage. Normally, air compressors on board
ships are:`,

    ,
    `-main air compressor`,
    `-topping up compressor`,
    `-deck air compressor`,
    `-Emergency air compressor`,
    `-Main air compressor`,

    `Main air compressor is used for supplying high pressurised air for starting of main and auxiliary
engines. The pressurised air generated by the air compressor is stored in air storage bottle. These
are high capacity compressors and the air pressure that is required from these compressors to
start the main engine is 30 bars.`,

    `Control air is also supplied from air bottle through a pressure reducing valve and a control air
filter. Normally they are twice in number and can be more than that for redundancy.
Topping up compressor takes up the lead to cover up for the leakage in the system. This means
that as soon as the air pressure in the system goes below a particular level, the topping up
compressor replenished the system with pressurized air.`
  ];
  heading = "Marine";
  multiList: Array<TextModel> = [
    {
      heading: "Deck air compressor",
      paragraphs: [
        `Deck air compressor is used for deck use and as service air compressor and might have a
separate service air bottle for the same. These are lower capacity pressure compressors as
pressure required for service air is in between the range of 6 to 8 bar.`
      ]
    },
    {
      heading: "Emergency air compressor",
      paragraphs: [
        `Emergency air compressor is used for starting auxiliary engine at the time of an emergency or
when the main air compressor has failed for filling up the main air receiver. This type of
compressor can be motor driven or engine driven. If motor driven, it should be supplied from
emergency source of power.`
      ]
    }
  ];
  constructor() { }

  ngOnInit() { }
}
